-- Generated by tools/render_maps.py: bounds of each template map texture.
return {
    ["germany"] = { min_x = -2000, max_x = 2015, min_z = -2000, max_z = 2015, width = 1338, height = 1338 },
    ["hungary"] = { min_x = -2000, max_x = 2015, min_z = -2000, max_z = 2015, width = 1338, height = 1338 },
    ["italy"] = { min_x = -2000, max_x = 2015, min_z = -2000, max_z = 2015, width = 1338, height = 1338 },
    ["poland"] = { min_x = -2000, max_x = 2015, min_z = -2000, max_z = 2015, width = 1338, height = 1338 },
    ["spain"] = { min_x = -2000, max_x = 2015, min_z = -2000, max_z = 2015, width = 1338, height = 1338 },
    ["test"] = { min_x = -208, max_x = 463, min_z = -608, max_z = 223, width = 672, height = 832 },
}
