name = classrooms_bridge
description = Bridge mod for the classrooms proxy plugin. Handles freeze, watch, teleport, and broadcast.
author = Fondazione Golinelli
title = Classrooms Bridge
optional_depends = playerphysics
