name = discovery_maps
title = Discovery Maps
description = Adds a fullscreen mapping GUI system with markers/waypoints
supported_games = *, minetest_game, nodecore, mineclonia, mineclone2, voxelibre
author = TomCon
release = 34183
